### ISSUE TITLE
Championfull.json not found

### ISSUE THREAD

**Issue by dryan426** [jkdanahy/League-Of-Cooldowns#1]
Is there a file missing from the repo? It doesn't seem to work when compiling.

**Comment by jkdanahy** [comment]
Just added a section to the readme for adding the static data to the application. Check that out and let me know if you have any issues.

**Comment by dryan426** [comment]
Thank you so much! If you want to add cooldown reduction to the abilities, here is this https://docs.google.com/spreadsheets/d/1RfI808e0Zc3NJdXmD8J46VdGlDykDifY1k0KgXrijHA/edit#gid=1377705543

**Comment by jkdanahy** [comment]
Thanks! We're currently working on restyling everything, but CDR is definitely next on the list, so I'll keep this bookmarked for reference.

**Comment by dryan426** [comment]
if you want I'll try to add a database and integrate it.

**Comment by jkdanahy** [comment]
I think it might make more sense to just do the math on the client side (cd * (1 - (cdr *.01)).
